### ISSUE TITLE
Not all populated Detect fields listed on documentation.

### ISSUE THREAD

**Issue by shalecraig** [madrobby/zepto#1015]
The [detect module](http://zeptojs.com/#Detect module) documentation lists [0], the code populates[1], and unit tests verify [2].

The key differences are:
* `$.browser.webkit`
* `$.os.wp`
* `$.os.osx`

I also noticed that the unit tests are hard to add to, and adding tests is ad-hoc - not every test asserts that every attribute is correct. Would you see a PR to refactor unit tests as friendly?

[0]
* `$.os.phone`
* `$.os.tablet`
* `$.os.ios`
* `$.os.android`
* `$.os.webos`
* `$.os.blackberry`
* `$.os.bb10`
* `$.os.rimtabletos`
* `$.os.iphone`
* `$.os.ipad`
* `$.os.ipod`
* `$.os.touchpad`
* `$.os.kindle`
* `$.browser.chrome`
* `$.browser.firefox`
* `$.browser.safari`
* `$.browser.webview`
* `$.browser.silk`
* `$.browser.playbook`
* `$.browser.ie`
* `$.os.version`
* `$.browser.version`

[1]
* `browser.chrome`
* `browser.firefox`
* `browser.ie`
* `browser.playbook`
* `browser.safari`
* `browser.silk`
* `browser.version`
* `browser.webkit`
* `browser.webview`
* `os.android`
* `os.bb10`
* `os.blackberry`
* `os.ios`
* `os.ipad`
* `os.iphone`
* `os.ipod`
* `os.kindle`
* `os.phone`
* `os.rimtabletos`
* `os.tablet`
* `os.touchpad`
* `os.version`
* `os.webos`
* `os.wp`

[2]
* `browser.chrome`
* `browser.firefox`
* `browser.ie`
* `browser.playbook`
* `browser.safari`
* `browser.silk`
* `browser.version`
* `browser.webkit`
* `browser.webview`
* `os.android`
* `os.bb10`
* `os.blackberry`
* `os.ios`
* `os.ipad`
* `os.iphone`
* `os.ipod`
* `os.kindle`
* `os.osx`
* `os.phone`
* `os.rimtabletos`
* `os.tablet`
* `os.touchpad`
* `os.version`
* `os.webos`
* `os.wp`

**Comment by madrobby** [comment]
Closing this because there was no response to our questions in a while. Feel free to reopen with the requested information!
