### ISSUE TITLE
IE11 on a non-touch PC returns true for $.os.tablet

### ISSUE THREAD

**Issue by dannycochran** [madrobby/zepto#1029]
There may not be anything to be done about this, but the user agent for IE11 on my Windows 8 VM is:

Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; Tablet PC 2.0; rv:11.0) like Gecko Trident/7.0; Touch; .NET4.0E; .NET4.0C; Tablet PC 2.0; rv:11,11

Thus registering true for &.os.tablet... not sure if there could be an additional line of logic to differentiate between tablet IE11 and desktop ie11?

**Comment by madrobby** [comment]
Closing this because it seems to be impossible to detect this correctly. I'd welcome a PR that fixes this however; any takers?
