### ISSUE TITLE
zepto.touch  click twice can trigger  tap event

### ISSUE THREAD

**Issue by memoryza** [madrobby/zepto#1051]
i touch page element twice when the dom event trigger;
code like this : $(document).on('tap', 'element', func);

i find the code 【 if (deltaX < 30 && deltaY < 30) {】  line at  zepto.touch 119;
deltaX,deltaY value  is 34,32,0 and so on. 
i want know 30px is standrand value.

**Comment by altbdoor** [comment]
> i touch page element twice when the dom event trigger;
> code like this : $(document).on('tap', 'element', func);

I'm sorry, but I do not understand the first part of the question.

> i want know 30px is standrand value. 

If I may guess, Zepto is following jQuery's standard of 30px before considering the event as a swipe. Please refer to [this link](http://www.w3schools.com/jquerymobile/jquerymobile_events_touch.asp).

**Comment by memoryza** [comment]
this is one question,i find deltaX/Y value more than 30px when my website built in the origin-App。it was found in the wechat(platform:  ios 7,iphone5s)

**Comment by altbdoor** [comment]
Can you try with other libraries (for example, [jQuery Mobile](http://api.jquerymobile.com/tap/)) to see if the deltaX/Y values are different from Zepto's?

If you want to change the value of 30px, #271 recommends that:

> ...build your own version of Zepto with a copy of the touch.js module customized to your needs.

**Comment by memoryza** [comment]
ok,i will try,thank you

**Comment by madrobby** [comment]
Closing the ticket because it's a question, not a big report.
