### ISSUE TITLE
scrollTop() returns undefined, but in jQuery works fine

### ISSUE THREAD

**Issue by Todd-Werelius** [madrobby/zepto#1056]
I have a small plunkr example that causes an element to stick to the top when it scrolls up 

In jQuery scrollTop() for the document called within onScroll works fine, but in Zepto 1.1.6 it returns undefined

Here is a plunkr using zepto, you can comment out the zepto reference and uncomment the jquery link to see it start working. 

http://plnkr.co/edit/rk2cRNjFaICWnHU0YTWa?p=preview

**Comment by madrobby** [comment]
Closing this because we’re not interested in full jQuery compatibility for any price and there's a simple native DOM API.
