### ISSUE TITLE
Package.json needs a version bump

### ISSUE THREAD

**Issue by boye** [madrobby/zepto#1067]
On zeptojs.com the download link refers to version 1.1.6. Yet, in package.json there is still a reference to 1.1.4.

**Comment by mislav** [comment]
We're not publishing an npm package, so we're only using `package.json` for dev dependencies. I would say that a version out of date is not a big deal.

**Comment by boye** [comment]
True, it's not a big deal. Though, the outdated version reference is also located in the `make` file as variable for generating the header in the build file. Therefore it would be nice to keep it consistent with the current version :)
