### ISSUE TITLE
can the tap event add attribute like pageX pageY?

### ISSUE THREAD

**Issue by shushenghong** [madrobby/zepto#1070]
sometimes i need the tap position.

**Comment by madrobby** [comment]
This is outside the scope of the tap event. If you need this information I recommended using native touch events directly.

**Comment by gudoy** [comment]
I just faced the issue too while needing offsetX/Y of a tap.
Why not retain the touchstart props and propagate them to the tap event as it is just more or less a faster 'click' event? I think this would make sense.
