### ISSUE TITLE
"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object.."

### ISSUE THREAD

**Issue by sourc7** [madrobby/zepto#1071]
Hi, I'm currently work with a project using zepto.js as Javascript Library but when I open the Firefox's developer tools a warning show: 

"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create" - zepto.js

Are there any performance impact? or could you improve the zepto.js code?

**Comment by madrobby** [comment]
Please try using thee latest `master` branch version. There should be no warning.

**Comment by mislav** [comment]
We're still overriding `.prototype` here: https://github.com/madrobby/zepto/blob/28896e3eead99e8556ecbbd2a0b1bee9ac659a21/src/zepto.js#L891

Workarounds welcome, if they achieve our desired outcome with regards to using `$.zepto.isZ`, `$.zepto.Z` and related.

**Comment by madrobby** [comment]
@mislav Ah, wasn't aware of that.

**Comment by madrobby** [comment]
@mislav I don't think this is what the error message refers to tho, we're setting the prototype of a constructor method, not mutating the prototype of an object.

**Comment by madrobby** [comment]
@mislav I'm also getting no warnings from Firefox about it on `master`. Closing ticket again.

**Comment by basiclines** [comment]
@madrobby Any plans to uplift the fix to any new stable version (1.6.1?) (instead of relying on master branch)

**Comment by askmatey** [comment]
@basiclines see https://github.com/madrobby/zepto/issues/1101
