### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by megawac** [madrobby/zepto#1076]
npm has `zepto@0.0.4` only at the moment. Can you run an `npm publish`

**Comment by mislav** [comment]
We [intentionally don't support nor publish](https://github.com/madrobby/zepto/issues/955#issuecomment-41026849) Zepto on NPM.

**Comment by megawac** [comment]
You should unpublish or deprecate the package on npm in that case

**Comment by mislav** [comment]
Sure, how do we deprecate a package?

I don't want to unpublish it because that would free up the name "zepto" for anyone to use, which I also don't want.

**Comment by megawac** [comment]
I'm on my phone but I'm pretty sure its just npm deprecate

**Comment by mislav** [comment]
Oh sorry, there's nothing we can do. Neither "zepto" nor "zeptojs" nor any other "zepto-*" packages on npm are owned by us therefore we can't make any changes to them. They're all unofficial.

**Comment by silverwind** [comment]
I'm sure the npm staff can lend you a hand there if you contact them. The jquery package had the same issue which they resolved eventually by unpublishing the offending module.

I sure would love to see zepto on npm. It not being there is the only reason I haven't switched yet.

**Comment by mislav** [comment]
> I'm sure the npm staff can lend you a hand there if you contact them.

Maybe, if we wanted to publish our own "zepto" package. But we don't. Ideally, I would unpublish "zepto" and "zeptojs" from npm and prevent others from registering the same names. But I don't think npm admins would let me do that.

> It not being there is the only reason I haven't switched yet.

I'm sorry that you find this as an obstacle to including a single extra `.js` file in your project.

**Comment by silverwind** [comment]
> I'm sorry that you find this as an obstacle to including a single extra .js file in your project.

I manage updates to all my frontend and backend packages through npm, and don't really want to go hunting for updates myself, when I can update all my deps in one swoop on the CLI, I'm sorry.

**Comment by joepie91** [comment]
> I'm sorry that you find this as an obstacle to including a single extra .js file in your project.

I feel like you misunderstand the issue. The problem isn't including an extra .js file (or that it's "too much work", as you stated in another thread), the problem is the inability to specify Zepto as an explicit dependency of anything, and the lack of modularity/consistency that can normally be derived from something being packaged.

It's not a matter of effort - it's a matter of consistency and versioning guarantees.
