### ISSUE TITLE
remove timeout handler after using xhr.abort?

### ISSUE THREAD

**Issue by cos2004** [madrobby/zepto#1077]
I set timeout in xhr config, timout handler will still be called when I call xhr.abort(), is it reasonable?

**Comment by madrobby** [comment]
Hi @cos2004, two questions:

1. Could you please provide a complete failing example? You can use a site like https://jsfiddle.net to provide that.

2. How does this behave on jQuery?

**Comment by mislav** [comment]
I can't reproduce this. Aborted xhr definitely [cleans up the timeout handler](https://github.com/madrobby/zepto/blob/0f2ab27c0c2a586915b577eab5e99d4e1e8fca45/src/ajax.js#L259) after it's done. If you are seeing something different, please share the code that demonstrates the issue! Thank you

**Comment by cos2004** [comment]
Hi @madrobby , I make a test via "v1.2.0", but this issue seems to have been resolved, as you know this issue post 1 year ago, thanks all the same :)
