### ISSUE TITLE
[bug]ajax crossDomain bug

### ISSUE THREAD

**Issue by zwlijun** [madrobby/zepto#1078]
When cross-domain AJAX in use, there will be an exception set by xhrFields withCredentials property. After calling xhrFields into open () method is normal.

**Comment by cos2004** [comment]
FYI #921

**Comment by mislav** [comment]
Thanks @cos2004.

@zwlijun: does your experience match the referenced issues? Which browser is this on?

**Comment by zwlijun** [comment]
@mislav in android webview. 
the same to @cos2004

**Comment by mislav** [comment]
OK, then closing as duplicate report.
