### ISSUE TITLE
No slideUp / slideDown functions?

### ISSUE THREAD

**Issue by andreszs** [madrobby/zepto#1079]
Classes manipulation and smooth toggling ob objects with the slideUp / slideDown functions is very essential these days. I was very disappointed to see this library is 25 KB in size, and the very first function I tried returns `undefined`.

I rather not switch to jQuery and its 92 KB just for using essential sliding functions, is there some way to add these functions into Zepto easily? Thanks.

**Comment by mislav** [comment]
Hi, we offer the optional [`fx_methods.js` module](https://github.com/madrobby/zepto/blob/28896e3eead99e8556ecbbd2a0b1bee9ac659a21/src/fx_methods.js) which is excluded by default but you can make your zepto.js build with it. However, it doesn't provide the `slideUp/Down` fuctions. We encourage you to implement those animations with CSS transitions and trigger them with classname switching in your webapp.

Or, if someone stepped in and implemented these functions in `fx_methods.js`, we would gladly review the submission. Thanks!

**Comment by emkayy** [comment]
Unfortunately slideUp / slideDown ist not possible to do with CSS transitions, since you can't animate to ``height: auto``. Therefore I'd appreciate these methods in native Zepto as well!
