### ISSUE TITLE
attr("form") returns <form> element when it should return null

### ISSUE THREAD

**Issue by benmonro** [madrobby/zepto#1080]
When I call .attr("form") on a form element that has no form='xxx' attribute, Zepto appears to be returning the parent object rather than 'null.'  I've created a jsbin that highlights the problem.  I have 2 text fields.  One insdie the form without the form attribute and the other outside the form with the form attribute.  You'll notice in the console that the 2nd one works correctly, but the first is showing the <form> element.  This isn't the way that jquery works so moving our code from jQuery to Zepto is stuck on this.

http://jsbin.com/fahuvisoje/1/

**Comment by mislav** [comment]
Yes, Zepto is falling back to the `.form` property if it doesn't find the attribute, and it seems that jQuery doesn't do that.

From jQuery docs:

> **As of jQuery 1.6,** the `.attr()` method returns undefined for attributes that have not been set. To retrieve and change DOM properties such as the checked, selected, or disabled state of form elements, use the `.prop()` method.

**Comment by benmonro** [comment]
ok so are you saying  i found a valid bug? :)

**Comment by mislav** [comment]
Yep thanks for reporting! We probably need to stop falling back to reading the property. This would require adding new tests and possibly changing some old ones. Care to try out submitting a pull request?

**Comment by benmonro** [comment]
sure thing

**Comment by benmonro** [comment]
I had it fall back to prop() which is what jquery does as well...

**Comment by benmonro** [comment]
oh didn't add any tests though.  sorry... should i resubmit?
