### ISSUE TITLE
Error with selecting direct children only

### ISSUE THREAD

**Issue by dschu-lab** [madrobby/zepto#1097]
When trying to select only the direct children of an known element, I get the following error:
SyntaxError: An invalid or illegal string was specified

I've made to codepens. One with a working jQuery example and another with my error.

jQuery: http://codepen.io/anon/pen/XJwQrm?editors=101
Zepto: http://codepen.io/anon/pen/MYdRgg?editors=101

Any ideas how to fix this or make a workaround?

**Comment by mislav** [comment]
Zepto uses browser's native CSS selector engine under the hood, while jQuery uses a custom selector engine called Sizzle. The native selector engine doesn't support queries that start with a combinator; i.e. you can't do this:

```js
element.querySelectorAll("> li")
```

The solution is to either rewrite your code to instead perform a query like this:

```js
// recommended solution
$(".mainList > li")
// or
$(".mainList").children("li")
```

Or you could bundle the optional "selector" Zepto module and be able to perform `"> li"` queries, but that implementation is hackish and should only be used as a last resort, e.g. when you don't have the ability to change the code that makes the queries and you need to support them.

**Comment by mislav** [comment]
See #730 for more discussion.
