### ISSUE TITLE
Release 1.1.7

### ISSUE THREAD

**Issue by askmatey** [madrobby/zepto#1101]
In order to use #1026 I am awaiting the release of `1.1.7`. What's the roadmap?

**Comment by mislav** [comment]
We can't really tag it as v1.1.7 because it's a substantial change. It has to be at least v1.2 in my opinion, but @madrobby suggested even v2.0.

We don't have a set roadmap. We could make a release at any time, but before each release we always need help triaging open issues/PRs so that each release includes at least a bunch of bug fixes.

**Comment by askmatey** [comment]
Any updates ?

**Comment by basiclines** [comment]
@mislav I believe this is an important change to include in the next release as it has been fixed some months ago and have an impact in performance. I can help you guys triaging open issues/PR in order to speed up the uplift if that's your bottleneck.

**Comment by mislav** [comment]
Yes, we'd appreciate helping triaging issues. Basically, we are interested in which quick fixes we can do for v1.1.x, and which feature changes might be useful for a next v1.2 or major release. You could compile a list in this thread.

**Comment by richardhinkamp** [comment]
a 1.1.7 release would be nice, since #1036 hasn't been included in a released version yet, so I have to rely on a custom version at the moment

**Comment by madrobby** [comment]
Closing this as it's not really an issue as such. I do agree that we should release a new version very soon.

@basiclines @richardhinkamp @askmatey We can release faster if we get help triaging issues. I've already gardened quite a bit today, but some issues need confirmation, can be closed and/or patches and tests can be written. We'd love some help to get releases done quicker! :)
