### ISSUE TITLE
src/touch.js touch.el.trigger  bug

### ISSUE THREAD

**Issue by Superman-wc** [madrobby/zepto#1103]
'undefined' is not an object (evaluating 'touch.el.trigger')

use  touch.el && touch.el.trigger()

PS. 

swipeTimeout = setTimeout(function() {
            touch.el && touch.el.trigger('swipe')
            touch.el && touch.el.trigger('swipe' + (swipeDirection(touch.x1, touch.x2, touch.y1, touch.y2)))
            touch = {}
          }, 0)

**Comment by paper** [comment]
我也遇到了！！！求fix！！！

please fix it~
