### ISSUE TITLE
Cannot install via jspm

### ISSUE THREAD

**Issue by togakangaroo** [madrobby/zepto#1107]
This breaks when trying to install via [jspm](http://jspm.io/). I believe the only change needed is to update the `"main"` key in `package.json` so that it points at the correct file.

**Comment by mislav** [comment]
And which is the correct file to point to?

**Comment by togakangaroo** [comment]
Whatever file you expect people to include. I see the examples point to src/zepto.js so probably that.

**Comment by mislav** [comment]
We expect people to build their own customized file from individual modules. We don't include in git source any particular file that is ready to be used in apps. `src/zepto.js` is just core functionality but doesn't include many essentials, such as event handling.

This is why we can't support package managers at the moment. However, Zepto is available from Bower.

See https://github.com/madrobby/zepto/issues/955#issuecomment-41026849
