### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by yyjazsf** [madrobby/zepto#1108]
如果页面不存在任何符合条件的元素，使用on绑定事件，之后用js添加的元素，委托事件无效
 $(document).on('click','.item',function(){\*...*\})

If the page does not exist any qualifying elements, 'on' the event delegate void

**Comment by madrobby** [comment]
Closing this issue because we can't help you without more information or a failing code example. I'd recommend using a site like http://codepen.io to show the failing code so we can debug, help and explain.
