### ISSUE TITLE
$.css({property: value, property2: value2,...}) returns undefined if selector returns an empty zepto collection object.

### ISSUE THREAD

**Issue by luckymargi7** [madrobby/zepto#1109]
`$('.existingDiv').css({'top': 0, 'position': 'fixed})` returns `[]` as it should. However `$('.notExistingDiv').css({'top': 0, 'position': 'fixed})` returns `undefined`. I'd expect the return of `.css({...})` to be the same as `$('.notExistingDiv').css('top', 0)` which correctly returns `[]`.

**Comment by tremby** [comment]
I just hit the same issue.

**Comment by madrobby** [comment]
I believe this might be a bug—need to confirm and test jQuery API with this.

**Comment by mislav** [comment]
Fixed in 991dabd1c9b7e25d2c6cff836fb75be70a8fadd6
