### ISSUE TITLE
Events with dot doesn't work

### ISSUE THREAD

**Issue by alejo-jm** [madrobby/zepto#1119]
+ Hello team, for example another library have this:  
var event = document.createEvent('Event');  
event.initEvent('Some.event', true, true);  
document.dispatchEvent(event);  
+ In zepto we do this  
$(document).on('Some.event', callback); //callback never called  
document.addEventListener('Some.event', callback); //callback is called  
+ The problem (event.js)  
Line 54 --> var handler   = parse(event); //return object {e:'Some', ns:'event'}  
Line 76 --> element.addEventListener(realEvent(handler.e), handler.proxy, eventCapture(handler, capture)) //hander.e is 'Some' must be 'Some.event'  
  
thanks.

**Comment by madrobby** [comment]
Please use a different separation character. Maybe ':' or '_'.
