### ISSUE TITLE
the touch module bug

### ISSUE THREAD

**Issue by PromeYang** [madrobby/zepto#1128]
in the ios system ,
if quick swipe two times , will throw a error,
the code in touch.js is 

swipeTimeout = setTimeout(function() {
            touch.el.trigger('swipe')
            touch.el.trigger('swipe' + (swipeDirection(touch.x1, touch.x2, touch.y1, touch.y2)))
            touch = {}
}, 0)

put the code exec in the setTimeout queue , 
the first time will do '  touch = {} ' 
and the second time , will not find the touch.el 

so , hope to fixed this problem

**Comment by PromeYang** [comment]
no body handle this ?

**Comment by madrobby** [comment]
Hi there! Could you please provide a complete failing example? You can use a site like https://jsfiddle.net to provide that. Without a failing example that we can immediately investigate we can’t reproduce the problem and can’t find and fix the issue. Thank you!

**Comment by yuezk** [comment]
This issue might have been fixed by #1182
