### ISSUE TITLE
selector.js,sel.replace report an console error,but it works,don't know why

### ISSUE THREAD

**Issue by xhxno36** [madrobby/zepto#1132]
i just use zepto builder to build the zepto，include selector.js and other modules.
when i run the script,it can work,but chrome get a console error,shows that sel.replace is not a function.
I set the break，check out zepto.js in function process(sel,fn){sel.replace(/=#\]/g, '="#"]')}.
sel.replace is not a function,
check out that sel is an object,not a string,so the error came out.
html
<span class="js_plus">+</span>
script:
$(".js_plus").click(function(){
// code goes here
})
browser
chrome 45.0
fifefox 40

**Comment by xhxno36** [comment]
html
&lt;span class="js_plus"&gt;+&lt;/span&gt;

**Comment by madrobby** [comment]
Closing this issue because we can't help you without more information or a failing code example. I'd recommend using a site like http://codepen.io to show the failing code so we can debug, help and explain.
