### ISSUE TITLE
No "main" field in package.json

### ISSUE THREAD

**Issue by code-artisan** [madrobby/zepto#1134]
我今天用Webpack + ES6 + React编写项目时，选择用Zepto来操作DOM，当
```js
import $ from 'zepto';
```
一直报错：Module not found: Error: Cannot resolve module 'zepto' in xxx，几番查找之后，才知道是Zepto项目下的package.json并没有main: "xxx/zepto.js"。。。😂😂😂

Em, My English is not good, I'm sorry for that.

**Comment by weisd** [comment]
SB

**Comment by code-artisan** [comment]
> SB

Hey, what wrong with you?

**Comment by madrobby** [comment]
We don't support JavaScript loaders. See the README for an explanation and details.
