### ISSUE TITLE
Events not working after custom build

### ISSUE THREAD

**Issue by ivvanov** [madrobby/zepto#1141]
If using a default zipto.min.js - events are fired.
If building a custom zepto - using zeptobuilder or node.js - events doesn`t work.

**Comment by mislav** [comment]
Can you look at the first few lines of `zepto.js` and tell us which modules it was compiled with?

**Comment by ivvanov** [comment]
Hi, 
there`s the first line of zepto.min.js:
/*! Zepto 1.1.6 (generated with Zepto Builder) - zepto event ajax form ie detect - zeptojs.com/license */

**Comment by mislav** [comment]
That looks alright. What did you mean by "events doesn't work"?

**Comment by ivvanov** [comment]
$(".click-screen").on('click', exitHandler, false) - this event is not working;

**Comment by mislav** [comment]
What is the 3rd `false` argument supposed to be? How did you verify that `exitHandler` never got invoked?

Is it an option that you simply use zepto.js from the official release and not Zepto Builder?

**Comment by ivvanov** [comment]
May be this will help you to understand what is the 3rd argument:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
I have a "console.log()" inside the exitHandler function and it is not logged. I need the "detect" plugin, so that`s why I use a custom build.

**Comment by mislav** [comment]
I'm aware of the 3rd argument to `addEventListener`. However, you are not calling `addEventListener` aren't you? You are calling Zepto's/jQuery's `$.fn.on()` method, which doesn't support any arguments after the handler function.

Can you try without passing the 3rd argument and reporting back please?

**Comment by ivvanov** [comment]
Still not working, but I've switched to addEventListener. Not enough time for debugging. Thanks anyway :)
