### ISSUE TITLE
Cannot concatenate pseudo-selectors

### ISSUE THREAD

**Issue by cefn** [madrobby/zepto#1143]
In a Webdriver-driven test suite, the $ selector engine is being passed the following dynamically-generated selector (which works with JQuery) in order to validate text input has succeeded...

```css
section.content .entry_col textarea:eq(0):contains('Paul T')
```

...however, the Zepto selector engine (with the zepto, event, stack and selector modules added during build) seems to reject concatenated pseudo-selectors, even though the individual selectors themselves are supported. Misleadingly it throws the following error because :contains() is concatenated after :eq() ...

```
Failed to execute 'querySelectorAll' on 'Document': 'section.content .entry_col textarea:eq(0)' is not a valid selector.
```

**Comment by mislav** [comment]
Our jQuery pseudo-selector support through the optional `selector` module is very limited. It doesn't support all pseudo-selectors, and it doesn't support them when they appear in the middle of a CSS selector. As you discovered, we also don't support combining them.

We *might* be able to enable this functionality, but I'm not sure if we want to go down that road. The `selector` module is provided as a thin jQuery compatibility layer for people who are using relatively simple pseudo-selectors. Any more complex selector should be rewritten using a combination of standard CSS selectors and jQuery-like chaining constructs.

I welcome you to explore supporting combined pseudo-selectors like in your use-case and opening a pull request with this, but if it's too much added code and complexity, I'm afraid we'll rather just leave things as is. In that case, you would be forced to rewrite whatever is generating these selectors for you in your test suite.

**Comment by mislav** [comment]
Closing this because current jQuery-style pseudo-selectors support is rudimentary at best and we won't be working on improving it much further. Instead, it is advised that you use fewer pseudo-selectors in your code, and move towards combination of standard CSS selectors and jQuery/Zepto filtering functions instead.
