### ISSUE TITLE
`$().css(object)` should not return `undefined`

### ISSUE THREAD

**Issue by kaelzhang** [madrobby/zepto#1145]
`.css({height: 1, width: 2})` on non-existing element should return `this` instead of `undefined`, because when calling this, user intend to set the value but not to get the computed style of the element.

```js
$().css({
  height: 1
}).css({
  width: 1
});
``` 

- expected: ok, jquery does it so.

- actual: `Uncaught TypeError: Cannot read property 'css' of undefined`

**Comment by mislav** [comment]
Good catch! Thanks for the pull request.
