### ISSUE TITLE
contat method return a normal Array instance?

### ISSUE THREAD

**Issue by zzzgit** [madrobby/zepto#1147]
```
var spans=$("span");
var anchors=$("a");
var sa=spans.concat(a);
sa.not("a");//TypeError: sa.not is not a function
```
the `concat` method return a normal `Array` object,instead of a zepto collection?

**Comment by mislav** [comment]
`concat` is an internal function for Zepto and shouldn't be used. That's [even documented with 💔](http://zeptojs.com/#concat).
