### ISSUE TITLE
.on doesn't work on a webapp of IOS 

### ISSUE THREAD

**Issue by ceemomx** [madrobby/zepto#1148]
`$('body').append("<div class='message reply-message'>\
         <div class='tip-img'><img /><b>balabala</b></div>\
         <div class='tip-content'>\
             balbala<span> </span>balabala\
             <div class='tip-btn'><a class='close-reply-message'>balabala</a><a class='comment-receive'>balabala</a></div>\
         </div>\
         </div>");`

`$('body').on('click', '.comment-receive', function () {
       //some code here
    });
})`

error: 'TypeError: undefined is not an object (evaluating \'b.el.trigger\')',
  file: 'http://127.0.0.1:3004/js/lib/zepto.min.js',
  line: '2',
  userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B466 (5215599088)'

but it can fixed like this `<a class='comment-receive' onclick=''>balabala</a>` . just adding a blank `onclick=''`

**Comment by tvainisi** [comment]
by the way the onclick='' fix breaks the click tap behavior in windows phone 7.1.

**Comment by madrobby** [comment]
I know it's been a while, but could you put this up on a live site? I'd recommend using a site like http://codepen.io to show the failing code so we have an easier time debugging this.

**Comment by madrobby** [comment]
Closing this because lack of response. Feel free to reopen with the requested information!
