### ISSUE TITLE
$.ajax when callback is same,the js  bug

### ISSUE THREAD

**Issue by xhmz** [madrobby/zepto#1154]
when  ajax callback is same , js error  [jsonp1 is not a funciton] in console sometime.
after  look up the  source , find that when the first request in load slowly,after the second window['callback'] is defined, in t.ajaxJSONP { t(a).on("load error", function (e, n) { ***window['callback'] = u(this u isundefined)**}},the window['callback'] = u(this u isundefined) will cover the second window['callback'] is defined,so when response(jsonp1() ) is execute,jsonp1 is undefined,
  
![image](https://cloud.githubusercontent.com/assets/8199554/11649755/4a27b5a0-9dbd-11e5-989a-6dff5734d732.png)

![r](https://cloud.githubusercontent.com/assets/8199554/11649843/4d9051a6-9dbe-11e5-9445-44a0c63ed43c.jpg)

**Comment by mislav** [comment]
I'm not sure what are you describing.

Can you post some code that demonstrates the problem? Are you using the latest version of zepto.js?

**Comment by xhmz** [comment]
![Uploading QQ截图20151209140011.jpg…]()

**Comment by xhmz** [comment]
function foo() {
	$.ajax({
		url :url1,
		dataType : 'jsonp',
		jsonp : 'callback',
		jsonpCallback : "jsonp2",
		timeout : 1000,
		success : function () {}
	});
	
	$.ajax({
		url :url2,
		dataType : 'jsonp',
		jsonp : 'callback',
		jsonpCallback : "jsonp2",
		timeout : 1000,
		success : function () {}
	});
}

in  chrome console  :    Uncaught TypeError: jsonp2 is not a function

**Comment by xiaoxintiaoda** [comment]
I get the same error,how to solve

**Comment by cristicVictory** [comment]
the same problem

**Comment by madrobby** [comment]
@xhmz @xiaoxintiaoda @cristicVictory Could you please post an example that shows the problem with your complete code, reduced to a minimum? With just some short snippets we can unfortunately not help you, because we can't reproduce and see the issue.

**Comment by cristicVictory** [comment]
var jsonpID =0,--->var jsonpID = new Date().getTime(), can fixed it.

**Comment by cristicVictory** [comment]
ajax.js file 
jsonpID = 0 ---> jsonpID = new Date().getTime()
the bug fixed

**Comment by mislav** [comment]
@xhmz It is your responsibility to not set the same `jsonpCallback` name for multiple requests running in parallel; otherwise you risk the error you were seeing in this case.

This is expected behavior and not something we need to fix. If you don't want to run into this, don't set `jsonpCallback` to a static string.

**Comment by xhmz** [comment]
thanks
