### ISSUE TITLE
how can I get same effect Jquery $().slideToggle() from zepto

### ISSUE THREAD

**Issue by chanakaeng** [madrobby/zepto#1156]
I have a code in Jquery as below;
$("#id").slideToggle('fast');
$("#id").promise().done($('html, body').animate({scrollTop: $(document).height()}, 200));

I start to use Zepto js instead of Jquery, so now I'm using below code,
$("#id").toggle();

How can I get the same effect like Jquery code from Zepto, in zepto .promise() is not defined.

I asked this in http://stackoverflow.com/questions/34215775/how-can-i-get-same-effect-jquery-slidetoggle-from-zepto

**Comment by madrobby** [comment]
We don't support `slideToggle`. You'll need to implement your own code for this.
