### ISSUE TITLE
ajaxBeforeSend may not work

### ISSUE THREAD

**Issue by linxixuan** [madrobby/zepto#1165]
Sometimes I need rewrite xhr url before ajax called;
So, I use code like this:
```javascript
// add event listener
$(document).on('ajaxBeforeSend', function(event, xhr, settings) {settings.url = 'http://www.foo.com';});

// call an ajax
$.ajax({url: "http://www.bar.com"});
```
In fact, zepto still send xhr to `www.bar.com`

**Comment by wwlsascha** [comment]
+1

**Comment by madrobby** [comment]
Does this work as you expect when using jQuery?

**Comment by mislav** [comment]
This should be working since 23d1879d55e89b4a375aaa1aefd71ff2582deabc. We have tests for this. Please provide evidence that it doesn't work for you if you want to reopen this issue. Thanks!
