### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by bianjp** [madrobby/zepto#1167]
Currently the latest [npm zepto package](https://www.npmjs.com/package/zepto) is v1.0.1, which is quite old.

Could you please update it?

In addition, is that possible to include every module as a single file in the published package so we can use any module as needed?
It's so annoying that we can't use bower or npm package if the default included modules couldn't meet our needs.

**Comment by mislav** [comment]
Just published zepto@1.1.6, which was our current stable release. We are working on 1.1.7 and 1.2.0 which are slated to get released very soon. Stay tuned!
