### ISSUE TITLE
null should be pass on to the function?

### ISSUE THREAD

**Issue by zzzgit** [madrobby/zepto#1176]
https://github.com/madrobby/zepto/blob/master/src/zepto.js#L768

why use `===` here instead of `==`?
it will treat `null` as a given value.

**Comment by madrobby** [comment]
Hey @zzzgit, please stop using the issue tracker merely to ask questions about the source code. The issue tracker is a place to report bugs (including detailed steps to reproduce them) and for future features.

We have only limited time to look at and comment on reported issues, so we ask you to take your time and research issues thoroughly before reporting them. If you suspect this is a bug with jQuery compatibility, you can add test how jQuery behaves and add a test and patch to Zepto and submit a pull request (if there is indeed a problem).
