### ISSUE TITLE
$('.add.mclass').addClass(function(index,oldclassname){alert(oldclassname);})

### ISSUE THREAD

**Issue by stevenkaiwang** [madrobby/zepto#1178]
<div class="add mclass"> </div>
$('.add.mclass').addClass(function(index,oldclassname){alert(oldclassname);})

error info: 
Uncaught TypeError: Cannot read property 'split' of undefined(anonymous function) @ zepto.js:719(anonymous function) @ zepto.js:427$.fn.each @ zepto.js:426$.fn.addClass @ zepto.js:715(anonymous function) @ zepto.html:41

**Comment by madrobby** [comment]
We can't help of you don't give us a complete failing example of what you're doing. You can use a service like http://codepen.io for this.

Closing until there's a full working (or rather, failing) example that we can debug. Please also take the time to give your tickets a better title (not just a line of code).
