### ISSUE TITLE
Ajax request failed，parameter parsing errors!!!

### ISSUE THREAD

**Issue by git-lt** [madrobby/zepto#1188]
$.ajax     if pms like ` {index:0, length:5, name:'tv'}`
send real pms turned into "0=&1=&2=&3=&4=&5="

source code function of likeArray is judge wrong
like this better (view jQuery source 'isLikeArray')
```
function isArrayLike( obj ) {
	// Support: iOS 8.2 (not reproducible in simulator)
	// `in` check used to prevent JIT error (gh-2145)
	// hasOwn isn't used here due to false negatives
	// regarding Nodelist length in IE
	var length = !!obj && "length" in obj && obj.length,
		type = jQuery.type( obj );

	if ( type === "function" || jQuery.isWindow( obj ) ) {
		return false;
	}

	return type === "array" || length === 0 ||
		typeof length === "number" && length > 0 && ( length - 1 ) in obj;
}
```

**Comment by mislav** [comment]
Thanks for reporting! This is known as https://github.com/madrobby/zepto/issues/918 and we do want to fix it. We may need to take an approach similar to jQuery's. If you care about this being fixed sooner, you can always try submitting a pull request! In the meantime I'm closing this as duplicate.
