### ISSUE TITLE
Resize))

### ISSUE THREAD

**Issue by artemtr** [madrobby/zepto#1189]
hi)) Thanks for work. Use zepto every time. But i can't find "resize" in documentation, that use in Jquery ??
$("window").on("resize", function(){
// code......
})
Have analogue in Zepto ?

**Comment by madrobby** [comment]
This works the same as in jQuery. `$(window).resize(...)` or `$(window).on('resize', ...)`.
If it doesn't work for you, please post a failing example on a site like http://jsfiddle.net
