### ISSUE TITLE
$.ajax Total breakdown when you attempt to use it with Monet.js

### ISSUE THREAD

**Issue by denisbetsi** [madrobby/zepto#1192]
when Monet.js is included in the project, somehow it causes major interferences in zepto.js

I think it has something to do with extend calls, which then take on zepto.js prototypes and starts joining them into the settings being passed. 

The end results is :

zepto.js:1431 Uncaught TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 2 arguments required, but only 1 present.

`For example:
<script src='assets/js/zepto.js'></script>
<script>
    $.get('http://www.cnn.com/whatevs.html', function(response){
        $(document.body).append(response)
    });
</script>
<script src='assets/js/monet.js.js'></script>
<script>
    $.get('http://www.cnn.com/whatevs.html', function(response){
        $(document.body).append(response)
    });
</script>
`

1st run yields expected error : 
`XMLHttpRequest cannot load http://www.cnn.com/whatevs.html. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

The 2nd attempt yields an error of : 2 arguments required.

**Comment by madrobby** [comment]
Hi there! Could you please provide a complete failing example? You can use a site like https://jsfiddle.net to provide that. Without a failing example that we can immediately investigate we can’t reproduce the problem and can’t find and fix the issue. Thank you!

**Comment by mislav** [comment]
Monet extends `Object.prototype` which breaks absolutely everything in both jQuery and Zepto, and not just ajax behavior. You shouldn't use Monet with these libraries.
