### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by MikhailTatsky** [madrobby/zepto#1197]
Hi ZeptoJS owner.
Can you please provide us with following information.
We at FancyGrid (http://fancygrid.com) want to drop dependecy from JQuery and have self light
dom module.
In fact we have some good experiment thing, but it requires too much time keep it working.
We like you project for it's minimizing and stability.
Althought jQuery 3 appeared with slim build, it still is too big, but Zepto JS is smaller in 3 times.

But we see many not-answers on github repo issues and honestly before chosing ZeptoJS as core for our dom module, we need to make sure that project is live and has future.

**Comment by Harkaran** [comment]
Just submitted a pull request, https://github.com/madrobby/zepto/pull/1199 . I certainly hope this project is still alive!

**Comment by madrobby** [comment]
Hi there! Yes, the project is alive! :)
