### ISSUE TITLE
where can i get help with a extened modules ?

### ISSUE THREAD

**Issue by zzzgit** [madrobby/zepto#1198]
hello
there are several modules beside the 4 core modules 
now i want to use them 
but where can i get documentations of those modules?

**Comment by mislav** [comment]
This would be your best bet: https://github.com/madrobby/zepto#zepto-modules

Some extra modules add additional functions (as indicated), and some expand existing functions/features. If you're still not sure what a certain module does, look at its source code, and it will probably be immediately clear. Good luck!

**Comment by zzzgit** [comment]
iv read a part of the source code of these modules
i have a question,why only implement `pinch` event in IOS?

**Comment by mislav** [comment]
Not sure! Maybe at the time of writing, native `gesture*`events were either unavailable or unreliable on other platforms? @madrobby

**Comment by madrobby** [comment]
@mislav Definitely were only supported properly on iOS. I dimly remember that other browsers had the DOM API interfaces but if you used them it would 💥
