### ISSUE TITLE
it seems there is a wrong in the documentation

### ISSUE THREAD

**Issue by zzzgit** [madrobby/zepto#1205]
> text
> text()  ⇒ string
> text(content)  ⇒ self
> text(function(index, oldText){ ... })  ⇒ self v1.1.4+
> Get or set the text content of elements in the collection. When no content is given, returns the text content **of the first element** in the collection...

hello,i think there is a wrong
after i read the source code,i found that actually it return the joined text content **of all the elements** in the collection,not only the first one
pls have a look at the source code:
https://github.com/madrobby/zepto/blob/master/src/zepto.js#L640

**Comment by mislav** [comment]
Good catch! You are right. The documentation is out of date.

Want to make an [edit on the `gh-pages` branch](https://github.com/madrobby/zepto/blob/gh-pages/core/_posts/1900-01-01-text.md) and send us a pull request?

**Comment by zzzgit** [comment]
yes i have made a request
https://github.com/madrobby/zepto/pull/1206
