### ISSUE TITLE
$().click() is broken on Safari for iOS

### ISSUE THREAD

**Issue by ohcibi** [madrobby/zepto#1209]
On safari for iOS registering a click handler fails at this line: https://github.com/madrobby/zepto/blob/v1.2.0/src/event.js#L142

The error thrown is `attempt to assign readonly property`.

**Comment by mislav** [comment]
Thanks for reporting! Which iOS version is that?

Would you submit a PR that wrapps the offending line in a `try..catch` block to ignore the exception?

**Comment by ohcibi** [comment]
I'll try to do it tomorrow
