### ISSUE TITLE
'this' is not equal 'window' anywhere

### ISSUE THREAD

**Issue by haozi** [madrobby/zepto#1210]
when use webpack 

```
import $ from 'zepto'

```

https://github.com/madrobby/zepto/blob/v1.2.0/src/amd_layout.js#L6

![image](https://cloud.githubusercontent.com/assets/4150641/17630430/d1eb30a0-60f1-11e6-88be-aead669cdc83.png)

**Comment by Tonyhark** [comment]
I have the same problem
