### ISSUE TITLE
gesture.js depends on detect.js

### ISSUE THREAD

**Issue by zzzgit** [madrobby/zepto#1220]
http://github.e-sites.nl/zeptobuilder/

i use this tool to get a build online, but if i only select the module `gesture` leave `detect` been selected, there will be an error in the console when running the code.

**Comment by madrobby** [comment]
Hi there! This tool is not maintained by us. Can you please report this to the maintainer (https://twitter.com/_boye)?

By the way, creating builds is easy from the command line, see the `README`. :)
