### ISSUE TITLE
Help,Thanks

### ISSUE THREAD

**Issue by blacklike** [madrobby/zepto#1221]
Dear Mr Fuchs,
My name is wangyao,I am a student.My English is not very good, so please forgive me.In recent years, with the emergence of the new front-end technology has been developed from a simple front-end to the front end of the whole stack development. I have been concerned about your dynamic work all the time ,and always slam my heart,I want to ask you some questions about the front end of the study.

1. How can you keep innovate to do it ?
2. All to known,although the threshold of front-end development is lowly, but in fact very difficult to do well ，and it's harder to be world-famous like you. So I really want to know how can you stick?
3. As a white, I especially curious what's your daily life essential software ?
4. The development of the front end is now very fast , new technology is becoming more and more, as a novice white, I feel more and more difficult to learn , do you have this feeling when you're learning ? And how to overcome ? For we, do you have any suggestions?
5. What is your main concern in development ?

Looking forward to your early reply, Thank you!

Yours truly,
wangyao

**Comment by madrobby** [comment]
Hi there! This is an issue tracker for Zepto, not a public forum or private communication channel. Please do not use it for generic questions. It's easy to find my email address if you want to get into contact with me. Thank you.

**Comment by doterlin** [comment]
haha....这小伙子。

**Comment by TechQuery** [comment]
@doterlin “As a white”这种表述有歧义吧……？想必 @blacklike 要表达的是“作为一个小白（新手）”，而非“作为一个白人”……

**Comment by TechQuery** [comment]
@doterlin 

看了用户资料，是个女生。

她也是 @HappyFedClub 的成员，从版本库的内容来看，他们 **Web 前端学习**挺努力的~

@blacklike ，欢迎来 @fyyflab 交流~

**Comment by doterlin** [comment]
可以。加油
