### ISSUE TITLE
how to override the default method "data"

### ISSUE THREAD

**Issue by zzzgit** [madrobby/zepto#1223]
```
SET MODULES=zepto event data
npm run-script dist
```

i used these commands to get a customer build.
but when i use the method `$.fn.data`,it will run into the default method defined in the module `zepto` ,not the override version in module `data`.

**Comment by madrobby** [comment]
I've no idea what environment or system you're on. Feel free to reopen this issue with more details and expected vs. actual results (e.g. attach the generated zepto.js file, show what it says on the command line, etc.).
