### ISSUE TITLE
what is the purpose of yield ?

### ISSUE THREAD

**Issue by zzzgit** [madrobby/zepto#1224]
https://github.com/madrobby/zepto/blob/master/src/amd_layout.js#L7

anyone can tell me what is the purpose of this line?

**Comment by madrobby** [comment]
Hi there, this is used here to insert the concatenated zepto source into a file usable for module loaders: https://github.com/madrobby/zepto/blob/master/make#L45

Please try to avoid using the issue tracker for generic questions about the source code. Thanks!
