### ISSUE TITLE
$(el).css do not support low level browser

### ISSUE THREAD

**Issue by chenjinya** [madrobby/zepto#1230]
like this:
`$(".loading-center").css({
            animation: 'loading-center 6s linear forwards ',
        });
`
in iOS 8 or other android low level browser， it has no effect .
I have to write like this:
`$(".loading-center").css({
           '-webkit-animation' : 'loading-center 6s linear forwards ',
        });
`
or modify the $(el).css function , add `property = $.fx.cssPrefix + property;`

Read zepto's $.fx code , I found that  function 'animate' has cssPrefix feature. 
can '$(el).css' support this feature ?

I wish you replay. thanks.

**Comment by limeblack** [comment]
@chenjinya  to do this properly you would need to detect browser support for properties but that would be outside the scope for the project.

At minimum you would have to make a whitelist of what properties should be replaced but if that would be rather complex.

I sure there are example codes like this on stackoverflow.

Is this a convenience thing?

**Comment by madrobby** [comment]
Fwiw, iOS 8 market share is now less than a percent. I'd suggest to either not support animations on older devices, or just additionally also set the prefixed versions; or to use $.fx instead.
