### ISSUE TITLE
tap event triggered twice in chrome version 54.0

### ISSUE THREAD

**Issue by MarvinXu** [madrobby/zepto#1238]
I updated my chrome to 54.0.2840.71 m (64-bit), and all my page that include tap event went rogue. any one encountered the same problem?
![gif](https://cloud.githubusercontent.com/assets/7382357/20176871/d56c022a-a784-11e6-849d-16a04982d9f3.gif)

**Comment by lizhe2004** [comment]
madrobby, what's your plan for this issue?  I saw you added 'Bug' tag for this issue report.

**Comment by madrobby** [comment]
@lizhe2004 have you tried the latest `master` yet? I had some changes to the way touch events work. it might have solved this issue.
