### ISSUE TITLE
$.is should also accept nodes

### ISSUE THREAD

**Issue by almathie** [madrobby/zepto#1242]
On jQuery : $.is(arg) accepts either a selector (string) or a node.

Zepto correctly supports the case when the argument is a string selector, but crashes when the arg is a node.

Passing node in the is function is used within Bootstrap 3 and thus trying to use Zepto with bootstrap fails.

**Comment by mislav** [comment]
Thanks for letting us know! Would you attempt to make a pull request to solve this? It sounds like the fix shouldn't be too hard.

**Comment by madrobby** [comment]
Fixed in #1266.
