### ISSUE TITLE
How to use Zepto inside ReactJS components?

### ISSUE THREAD

**Issue by r3verser** [madrobby/zepto#1243]
When importing, or requiring got error like "Cannot read property 'createElement'" .

**Comment by r3verser** [comment]
Anyone?:confused:

**Comment by tokyo-jesus** [comment]
i'm using webpack and babel. installed `zepto` using `npm`.

```
import $ from 'zepto'
// some component
```

has this result

```
Uncaught TypeError: Cannot read property 'createElement' of undefined
    at eval (zepto.js:23)
    at eval (zepto.js:939)
    at Object.eval (zepto.js:4)
    at emptyArray (zepto.js:4)
    at eval (zepto.js:7)
    at Object.1057 (8.8.js:179)
    at __webpack_require__ (main.js:583)
    at fn (main.js:107)
    at eval (Checkbox.vue?./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0:7)
    at Object.1056 (8.8.js:169)
```

**Comment by KroniK907** [comment]
I'm still having this issue... Is there a better way to import zepto?

**Comment by albizures** [comment]
Hi, an easy workaround, if you are using webpack,  it is to use `imports-loader` like this:
```javascript
rules : [
     {
       test: require.resolve('zepto'),
       use: 'imports-loader?this=>window',
    }
]
```
source: https://webpack.js.org/loaders/imports-loader/#webpack-config-js

**Comment by httpiago** [comment]
Zepto is not optimized to work with react on the server side, it needs to access the "window" and "document", but you can use it in places you are sure will only be called on the client side:
```js
componentDidMount() {
  const $ = import('zepto')
    
  $('#root').find('#header').hasClass('show')
}
```
You can also use on dynamic components.
