### ISSUE TITLE
ajax auto guess mime bug

### ISSUE THREAD

**Issue by yanhaijing** [madrobby/zepto#1246]
function mimeToDataType(mime) {
        return mime && ( mime == htmlType ? 'html' :
          mime == jsonType ? 'json' :
          scriptTypeRE.test(mime) ? 'script' :
          xmlTypeRE.test(mime) && 'xml' ) || 'text'
      }

when `content-type` is `Content-Type:application/json; charset=utf-8`, please regexp

**Comment by madrobby** [comment]
Good catch! Do you want to try to add a PR and tests for this?

**Comment by madrobby** [comment]
I've checked the source code, and this method has since been augmented to only parse the non-charset part of mime types. This means the charset is silently ignored by Zepto. Closing this issue.

```function mimeToDataType(mime) {
    if (mime) mime = mime.split(';', 2)[0]
    return mime && ( mime == htmlType ? 'html' :
      mime == jsonType ? 'json' :
      scriptTypeRE.test(mime) ? 'script' :
      xmlTypeRE.test(mime) && 'xml' ) || 'text'
  }```

**Comment by yanhaijing** [comment]
nice
