### ISSUE TITLE
what does problem about : Uncaught TypeError: Cannot read property 'trigger' of undefined     at touch.js:110 

### ISSUE THREAD

**Issue by SamChristina** [madrobby/zepto#1248]
when I swipeUp/swipeDown in img on my H5 in chrome debugging, errorlog is logging "Uncaught TypeError: Cannot read property 'trigger' of undefined     at touch.js:110 ".
my project url is :http://cq.sina.com.cn/zt/2016/12/yh.html
is there any problem?
thx

**Comment by dukegod** [comment]
'Tap' also collapsed!!!
google version : 55.0.2883.87 m (64-bit)
use google browser as a emulated device.
when i tap the page , the error also appeared.

**Comment by SamChristina** [comment]
I guess this is problem about latest version of chrome

**Comment by think2011** [comment]
`Version 55.0.2883.95 (64-bit)`  same problem

**Comment by dukegod** [comment]
it works very well in my macPro (Sierra).

**Comment by SamChristina** [comment]
Well，setting in Chrome://flags,  disable the"#enable-pointer-events" can solve the problem
