### ISSUE TITLE
Touch.js error  ，（Please turn it off）

### ISSUE THREAD

**Issue by sunriseshow** [madrobby/zepto#1252]
chrome v 55.0.2883.95 (64-bit)   ，The latest version

I installed, the pages are used touch.js such mistakes

![image](https://cloud.githubusercontent.com/assets/8856011/21749691/b22383e6-d5de-11e6-8baa-5f5ba80723f2.png)

**Comment by yuezk** [comment]
@sunriseshow Please update zepto, it has been fixed in #1182

**Comment by madrobby** [comment]
Fixed in #1182.
