### ISSUE TITLE
Promise callbacks order of execution does not follow Promise/A+ Spec

### ISSUE THREAD

**Issue by ptbrowne** [madrobby/zepto#1253]
## Problem
 
```javascript
$.Deferred().resolve().promise().then(function () {
  console.log('2');
});

console.log('1')
```

outputs

```
2
1
```

Live on : http://jsbin.oom/havekum/1/edit?html,js,console,output

## Expectation

It should output

```
1
2
```

## Rationale

As well [summed up here](http://stackoverflow.com/questions/36870467/what-is-the-order-of-execution-in-javascript-promises) and following the [Promise/A+](https://promisesaplus.com/) spec, the callbacks
attached to a promise must be called alter the current thread of execution finishes.

> All .then() handlers are called asynchronously after the current thread of execution finishes (as the Promises/A+ spec says, when the JS engine returns back to "platform code"). This is true even for promises that are resolved synchronously such as Promise.resolve().then(...). This is done for programming consistency so that a .then() handler is consistently called asynchronously no matter whether the promise is resolved immediately or later. This prevents some timing bugs and makes it easier for the calling code to see consistent asynchronous execution.

Example of code where it matters:

```javascript
const doSomethingAsync = function () {
    return $.ajax({ url: 'http://blabla.com' });
};

const doSomethingSync = function () {
   return $.Deferred().resolve().promise();
};

const doSomething = function (sync) {
  if (sync) {
     return doSomethingSync();
  } else {
     return doSomethingAsync();  
  }
}
```

Here we can see that the promise interface hides well the fact that one implementation of
`doSomething` is synchronous. The problem lies when you try to do something a bit more
complicated. Example : You want that if `doSomething` is called a second time while the first call
has not completed (the returned promise has not been completed), the caller receives the first promise.

This approach is generalisable to all functions returning promises so you want to create a decorator.

```javascript
const debouncePromise = function (fn) {
  let ongoingPromise;
  return function () {
    if (ongoingPromise) {
      return ongoingPromise;
    }
    else {
      ongoingPromise = fn.apply(this, arguments).always(function () {
        ongoingPromise = null;
      });
    }
  };
};

// And now you should be able to use it like that
const debouncedDoSomething = debouncePromise(doSomething);
```

Here, there is a discrepancy between when `doSomething` is called with the `sync` argument or not. Since the `always` callback is called while the thread of execution has not finished, `ongoingPromise` will first be set to `null` in the `always` callback (since the `Deferred` is immediately resolved), and *then* it will take the value of the promise, which means that your `debouncePromise` function will always return the result of the first call.

Following the spec, the `always` callback should be called after the current thread of execution finishes, after the `ongoingPromise` value is set to the promise.

This is fixable by doing : 

```
ongoingPromise = fn.apply(this, arguments);
ongoingPromise.always(function () {
  ongoingPromise = null;
});
```

but it is very brittle as someone could easily refactor that into the first way of doing things.

I think that if the order of execution would always be the same (as in the Promise/A+ spec), it would be more coherent and easier to reason about.

What do you think ?

Thanks for Zepto !

**Comment by mislav** [comment]
Hi thanks for bringing this to our attention. We based the Deferred implementation on jQuery's behavior at the time which wasn't Promise/A+ compatible. I'm not sure if we should be changing it now, since it was only meant for compatibility with jQuery and not as a Promise polyfill.

In a browser that supports Promises (or, at least, loads a proper polyfill), any "thenable" object can theoretically be wrapped in a `Promise.resolve(obj)` and "converted" into Promise/A+ compatible behavior. So, I think we should maybe focus just on having a useful `then()` method and not aim to reimplement Promises.

**Comment by madrobby** [comment]
Closing this as I agree with @mislav here! Thanks for reporting this though.
