### ISSUE TITLE
Fork this repo under a new Zepto Github org

### ISSUE THREAD

**Issue by bmcminn** [madrobby/zepto#1258]
Considering a fork of this repo just to get some updates done... plenty of issues are still unresolved, and most of them are pretty old (eg: #1047). Curious if anyone is interested in opening up a Zetpo org to house this and possibly get @madrobby on board with turning it over to the community?

**Comment by SimonCropp** [comment]
@madrobby thoughts on this?

**Comment by NetOperatorWibby** [comment]
Someone should just do it and link back here.

**Comment by bmcminn** [comment]
And done: https://github.com/ZeptoJS

I'll see about getting a fork under there.

**Comment by bmcminn** [comment]
Alright, forked the original repo under the new @ZeptoJS org, as well I cloned the original repo into a new repo so we could track all future issues.

We'll need to see about submitting the new repo to NPM.
