### ISSUE TITLE
.attr() changed in 1.2.0

### ISSUE THREAD

**Issue by richardhinkamp** [madrobby/zepto#1261]
I just upgrade a project to 1.2.0 and caught a bug. Turns out `.attr()` changed it's return value when the attribute doesn't exist:
```
// 1.1.7
$('body').attr('non-existing'); // null
// 1.2.0
$('body').attr('non-existing'); // undefined
```
See: 
1.2.0: http://jsbin.com/tivozelili/edit?html,js,console,output
1.1.7: http://jsbin.com/nosafoniyu/1/edit?html,js,console,output

I guess this is as it should be when I read #148 and the applied fix. That only fixed the return value of `attr()` on an empty selector, not with a valid selector but not existing attribute.

Could this be added to the changelog of 1.2.0? This might break more apps.

**Comment by mislav** [comment]
This was changed in 85d475a525f08edab82a499be68809d04df1cce8. You're right that this was not explicitly stated in release notes. I've amended the release notes to indicate this change: https://github.com/madrobby/zepto/releases/tag/v1.2.0
