### ISSUE TITLE
outerHeight not supported

### ISSUE THREAD

**Issue by gnadelwartz** [madrobby/zepto#1268]
Hi,

I successfully mirgated my script to zepto and found one problem: .outerHeight() is not supported.
the migration also point me to the fact that .first() and .not() are faster than jquery :first and :not pseudo selector :-)

for the outerHeight problem I used the workaround from here (solution 2):
http://stackoverflow.com/questions/10787782/full-height-of-a-html-element-div-including-border-padding-and-margin

Performance of zepto is same as with jquery, may be a litte better.

**Comment by gnadelwartz** [comment]
as I mention, the of my userscript conversion to zepto was easy, this is the full diff:
https://greasyfork.org/de/scripts/24244-enstylerjs-develop/diff?v1=176309&v2=175801

**Comment by madrobby** [comment]
I think this is one of the more esoteric jQuery functions. You could easily support this in a Zepto plugin. Closing this unless there's more interest in adding it as a feature.
