### ISSUE TITLE
长整形$.prototype.data()错误

### ISSUE THREAD

**Issue by sprufu** [madrobby/zepto#1273]
HTML

```html
<div id="el" data-some-id="1295324335947271103"></div>
```

JavaScript

```javascript
console.log($('#el').data('someId'));
// 1295324335947271200
```

**Comment by lwdmengda** [comment]
前面加个字母试试？
`<div id="el" data-some-id="a1295324335947271103"></div>`

**Comment by madrobby** [comment]
Hi there! For the benefit of all Zepto users, please submit issues in English.

**Comment by TechQuery** [comment]
@sprufu 三年前的 Zepto v1.2.0 已在 3534050 解决了大数转换 bug，请说明你的版本号~
