### ISSUE TITLE
touch.js "swipe" events not firing

### ISSUE THREAD

**Issue by TuomLarsen** [madrobby/zepto#1276]
It seems that touch.js stopped firing "swipe" events. I get "tap" and "doubleTap" events, though. 

I also tried various versions of Zepto with:
http://tumult.com/misc/static/zepto-0.8/test/touch_functional.html
and the last version which worked was 1.0.

I'm on Chrome 56.0 with touch emulation in Developer Tools.

**Comment by roylabanon** [comment]
Same Here,
It was working with Samsung J7 (5.1.1) but not with Samsung S5 (6.0.1)

**Comment by emkayy** [comment]
Yes, same here, tap works, swipe doesn't.
Any quick fix I can apply?

**Comment by yangchao2015** [comment]
yes，same here ,but how to solve

**Comment by zenxds** [comment]
## my solution

open`chrome://flags`, and disable`enable-pointer-events`

**Comment by madrobby** [comment]
This should be fixed in d7e4cafd129cdb6223e6c3c60c7f6ccfc6750512. Please reopen this issue if you still have issues on the latest `master`.

**Comment by TuomLarsen** [comment]
I built it with Zepto Builder and in Chrome Developer Tools it works very nicely, thank you!
However, on iOS it seems to "skip" or not always fire swipe events. Also, it seems I cannot re-open the issue...
