### ISSUE TITLE
$(...).on is not a function

### ISSUE THREAD

**Issue by smileyby** [madrobby/zepto#1277]
```javascript
$('h1').on('click', function(e){
  console.log(1);
});
```
console show `Uncaught TypeError: $(...).on is not a function`
the latest version of zepto, run get this error. [test demo](https://smileyby.github.io/zeptoTest/)

**Comment by acz13** [comment]
You need to use the actual [zepto.js](http://zeptojs.com/zepto.js) library not `src/zepto.js` which is only part of the library without any of the components

**Comment by smileyby** [comment]
Thanks
