### ISSUE TITLE
Why does attr return a value when image source is empty?

### ISSUE THREAD

**Issue by eisbehr-** [madrobby/zepto#1286]
I've noticed this strage behavior. Can someone tell me why `attr` returns the current page url, when `src` is empty?

```HTML
<img src="" />
```

```JS
console.log($("img").attr("src"));
```

[**(Not-)Working example as fiddle.**](https://jsfiddle.net/rfvzbvo0/)

**Comment by ewwink** [comment]
old version of zepto 1.0rc1, use newer https://cdn.jsdelivr.net/zepto/1.2.0/zepto.js
