### ISSUE TITLE
Zepto Builder amd_layout bundle.

### ISSUE THREAD

**Issue by MarvinWilliam** [madrobby/zepto#1290]
I use [http://github.e-sites.nl/zeptobuilder/](url) to bundle zepto code.

but i  found this result is not like [http://zeptojs.com/zepto.js](url).

zepto builder does not handle amd_layout as expect.

it keep these lines in code.
```
(function(global, factory) {
  if (typeof define === 'function' && define.amd)
    define(function() { return factory(global) })
  else
    factory(global)
}(this, function(window) {
  YIELD
  return Zepto
}))
```

**Comment by madrobby** [comment]
Hi there! Please take up issues with the builder with the makers of it. Thanks!
