### ISSUE TITLE
TypeError: Attempted to assign to readonly property, in event.add method

### ISSUE THREAD

**Issue by atgwwx** [madrobby/zepto#1295]
in iphone 10.3, when i bind `input` event , it occurs error, like below:
```
<input id="input_age">
$('#input_age').on('input',function(){
         
        });
```
![eudlh](https://user-images.githubusercontent.com/4476814/27819597-93da0e12-60cd-11e7-81ca-421eed5ec7ea.jpg)

**Comment by xuorig** [comment]
Related: https://github.com/madrobby/zepto/issues/1256

Unfortunatly it seems like zepto has not been accepting Issues / PRs

**Comment by madrobby** [comment]
Duplicate of #1256 1256
