### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by DanielRuf** [madrobby/zepto#1321]
It would be great to have a new release. The last one was in 2016.

**Comment by DanielRuf** [comment]
Bump.

**Comment by briganti** [comment]
@sunnibfgi It looks like you are one of the last maintainers on this project. I will really appreciate a new version as I need this #1218 fix. Can you do something about it?

**Comment by DanielRuf** [comment]
There is an active fork under the ZeptoJS fork. You might want to ask there too.

https://github.com/zeptojs/zepto

**Comment by DanielRuf** [comment]
There is an active fork under the ZeptoJS fork. You might want to ask there too.

https://github.com/zeptojs/zepto.js
