### ISSUE TITLE
Zepto find selector not working when migrating from jquery to Zepto

### ISSUE THREAD

**Issue by anand-zarget** [madrobby/zepto#1325]
I have a html table like this <html>
<body > <table><tbody><tr><td>One</td></tr><tr><td>Two</td></tr> <tr><td>Three</td></tr><tr><td>Four</td></tr></tbody></table></body>
</html>

and iam using Zepto to find the element like  **$("tbody > tr:eq(2) > td:eq(0)")** which throws error even i included all the modules "Zepto event selector fx fx_methods"
**error:**
"Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': 'tbody > tr:eq(2) > td' is not a valid selector."

**Comment by madrobby** [comment]
You need to include the selector module to use jQuery CSS extensions. See the README on how to make custom builds.
