### ISSUE TITLE
select ID start with number is not a valid selector

### ISSUE THREAD

**Issue by ewwink** [madrobby/zepto#1333]
```
<div id="123id">
  <p>hello</p>
</div>
<script>
var aa = $('#123id p').html();
console.log(aa);
</script>
```

`SyntaxError: '#123id p' is not a valid selector`
but jQuery is fine.

**Comment by fangbinwei** [comment]
zepto use `document.querySelectorAll('#123id p')` to select the element node, and querySelectorAll needs valid CSS selectors. 

However, it seems that ID selectors are not allowed to start with a number.
`<style> #123id {background-color: red; }</style>` doesn't work either.
>[https://css-tricks.com/ids-cannot-start-with-a-number/](url)

I hope it can help you.

**Comment by shirenhu** [comment]
but you can use document.getElementById   to select the element

**Comment by madrobby** [comment]
Please fix your IDs to conform to the HTML standard.
