### ISSUE TITLE
not anymore '9.6k when gzipped'

### ISSUE THREAD

**Issue by gMan1990** [madrobby/zepto#1360]
1. https://zeptojs.com/
    ```text
    Download Zepto
     – 57.3k uncompressed, lots of comments
     – 9.6k when gzipped
    ```

2. support UserScript ? chrome tampermonkey
    ```
    // ==UserScript==
    // @require  https://zeptojs.com/zepto.min.js
    ```
    TypeError: Cannot read property 'createElement' of undefined

**Comment by DanielRuf** [comment]
It's not clear what this issue is about. Please clarify.
