### ISSUE TITLE
Can I use Zepto.js and Jquery.js together?

### ISSUE THREAD

**Issue by ramankashyap** [madrobby/zepto#302]
Hi Team,

I'm new to zepto framework. I was using only "anim" function from it. Now, I need to use a jquery plugin which requires jquery.js file. So, now I have both (zepto, & jquery) js files on my page which has broken the page.

Below is the exception:

TypeError: 'undefined' is not a function (evaluating '$('.ToolDraw')
                .addClass('closed')
                .anim({ translate3d: 50 + 'px, 0px, 0px' }, 0.5, 'ease-in')')

Do you have idea/suggestion? Am I missing something?

Thanks,
Raman

**Comment by ravindgo** [comment]
Thanks Mislav for the solution, it helped me :)
