### ISSUE TITLE
swipe* events are not working on Android 4 and Galaxy Nexus unless you suppress touchmove

### ISSUE THREAD

**Issue by gianni** [madrobby/zepto#315]
Hi,

I have problem with the swipeLeft and swipeRight events with some mobile devices ...
For example with a galaxy s2 and iphone 4 the swipe events function correctly ...
instead, with a galaxy note (android 2.3.4) and a galaxy s the swipe events don't function ...

Could you help me?
Where can i found a list of supported device?

Thanks in advance!

**Comment by shirlyLoveU** [comment]
@songhlc 
have you got a good method to fix the bug
