### ISSUE TITLE
Feature Request: Have a way to determine if an object is wrapped by Zepto

### ISSUE THREAD

**Issue by diazruy** [madrobby/zepto#349]
In jQuery, executing the following returns true:

``` javascript
$('<div></div>') instanceof jQuery //=> true
$('<div></div>') instanceof $ //=> true
```

This is useful in Jasmine for example when writing custom matchers where you want to test to see if an object has been wrapped by Zepto. However, in Zepto the following behaviour occurs:

``` javascript
$('<div></div>') instanceof Zepto //=> false
$('<div></div>') instanceof $ //=> false
```

Is it possible to allow comparable behaviour for Zepto?

**Comment by pacotole** [comment]
Great @danyaPostfactum !
Added `$.prototype = $.fn` and all plugins using `instanceof` works fine.
