### ISSUE TITLE
Missing way to delete data associated with an element, like .removeData() in jQuery

### ISSUE THREAD

**Issue by sourcebits-robertbiggs** [madrobby/zepto#589]
Although Zepto has the ability to set and get data in relation to using the data method as in jQuery, there is no way to remove data associated with a node. This leads to situations where data gets stored in relation to a node and there is no way to delete. During complex user interactions you might want to store and then remove data from a node based on the state of a widget. 

``` javascript
// Sets the element with data: important = 'very important stuff'
var obj = {value: 'very important stuff'}
$('#myDiv').data('important', obj)

// returns the value of 'important' on that node.
$('#myDiv').data('important')
```

**What's missing:**

``` javascript
// remove all reference to 'important' and its data from the node.
$('#myDiv').removeData('important')
```

See jQuery's documentation: [removeData](http://api.jquery.com/removeData/)

**Comment by redaxmedia** [comment]
This make data() useless, I suggest to add this to the core package!
