### ISSUE TITLE
Building Zepto with Node.js & grunt

### ISSUE THREAD

**Issue by Hupotronic** [madrobby/zepto#602]
I wanted to build Zepto last night but wasn't in the mood for installing Ruby, so I decided to do some work and port the build tools to [grunt](http://gruntjs.com) instead. You can find the results [here](https://github.com/Hupotronic/zepto) - just check out the [gruntfile](https://github.com/Hupotronic/zepto/blob/master/grunt.js) and usage instructions in the readme. I currently have the module listing, building and minifying working.

Now then, onto my question: Would Zepto be interested in this?

(I found #478, but the last comment there was six months ago. I didn't want to make a pull request yet since I haven't implemented automated unit testing, plus I'd like to see cowboy/grunt#453 fixed so there'd be no need to modify the header comments in all the `src` files)

**Comment by askmatey** [comment]
Try https://github.com/askmatey/grunt-zeptojs

```sh
$ npm i --save-dev grunt-zeptojs
```

```sh
grunt.loadNpmTasks('grunt-zeptojs');
```
