### ISSUE TITLE
css('webkitTransform', 'translate3d(320px, 0, 0)') not working

### ISSUE THREAD

**Issue by srohde** [madrobby/zepto#691]
With Zepto I need to do:

    $main.get(0).style['-webkit-transform'] = 'translate3d(320px, 0, 0)'

Expected usage (works with JQuery):

    $main.css('webkitTransform', 'translate3d(320px, 0, 0)')

**Comment by madrobby** [comment]
I think this is a non-issue now, because browsers widely support the standard `transform` property. If this is still an issue for you, please feel free to reopen, ideally with a patch. :)
