### ISSUE TITLE
Zepto.find() behaves differently from jQuery.find()

### ISSUE THREAD

**Issue by sergiolopes** [madrobby/zepto#730]
Test cases:

- Zepto: http://jsfiddle.net/yrabP/
- jQuery: http://jsfiddle.net/p8J42/

(I tested in Chrome only but it should be similar in all browsers)

Since Zepto uses querySelectorAll, it matches children elements differently that jQuery. `element.querySelectorAll` evaluates the selector relatively to the page context, not scoped to the element as jQuery does:

http://www.w3.org/TR/selectors-api/#examples0

Don't know what to do. Should Zepto not use querySelectorAll for find() and mimic jQuery's behavior? Or should Zepto be different than jQuery? In that case, people must know this difference since it can cause serious incompatibility problems for people migrating from jQuery to Zepto.

**Comment by madrobby** [comment]
Closing this because there was no response to our questions in a while (see #734). Feel free to reopen with the requested information! :)
