### ISSUE TITLE
I have a little doubt about the Offset method

### ISSUE THREAD

**Issue by caoren** [madrobby/zepto#778]
current code
var obj = this[0].getBoundingClientRect()
      return {
        left: obj.left + window.pageXOffset,
        top: obj.top + window.pageYOffset,
        width: Math.round(obj.width),
        height: Math.round(obj.height)
}
Why don't you back to bottom and right, these two properties getBoundingClientRect is returned.May be I don't understand Zepto's intentions

**Comment by xwenliang** [comment]
why to round width/height? this cause a bug when width/height was a decimal.
