### ISSUE TITLE
The delegate function is not supported in the QQBrowser/safari of iphone 4

### ISSUE THREAD

**Issue by feibinyang** [madrobby/zepto#876]
I test that the delegate function is not supported in the QQBrowser/safari of iphone 4.Event it's deprecated,but i think that will be better if it is fixed.Thanks.
For now, i fixed the bug by using the on function,bug the binding function did nothing.
For example:
$(el).on('click', function(evt){});  Just like this, then the delegate's function could be trigged.

**Comment by madrobby** [comment]
Closing this because this is stale and pretty old. Please feel free to reopen if necessary.
