### ISSUE TITLE
JSONP $.ajax fails if type is passed

### ISSUE THREAD

**Issue by arthurgouveia** [madrobby/zepto#884]
Hello.

I was using jQuery 2.0 for a mobile app, wrapped by PhoneGap and I had a JSONP call to an API which was working, but then when I switched to zepto.js, my requests were not sending any data anymore.

Turns out that I previously had a standard JSON call and had a type: 'post' set on the parameters of my ajax call. Once switched to JSONP, jQuery ignored this type and was making a GET request, as expected for a JSONP. Zepto still makes the GET request but sends no data. I'm wondering if that shouldn't be ignored in case a dataType: 'jsonp' was set and therefore avoid this data not being sent.

Can be reproduced here (create a requestbin for yourself if you don't want to see other people's):

Zepto: http://codepen.io/anon/pen/ljfhA
jQuery: http://codepen.io/anon/pen/cnvzh

**Comment by paranoidjk** [comment]
I came across this problem too.
 I understand that it's a `wrong` way to use jsonp whit POST，but I still hope that zepto can behavior just like jquery, which auto change POST to GET when datatype is jsonp. 

Can this PR acceptable ? maybe a console error to warning the developer.
