### ISSUE TITLE
Large number of errors seen on iOS7 devices under Zepto 1.1.2

### ISSUE THREAD

**Issue by kpdecker** [madrobby/zepto#899]
After updating to Zepto 1.1.2 we started seeing a massive number of these errors:

- TypeError: 'undefined' is not a function (evaluating 'e.isImmediatePropagationStopped()')
- 'undefined' is not a function (evaluating 'e.isImmediatePropagationStopped()')
- 'undefined' is not a function (evaluating 'r.isDefaultPrevented()')
- TypeError: 'undefined' is not a function (evaluating 'r.isDefaultPrevented()')

They all appear to be occurring under various iOS7 versions and we are not seeing a spike in generic "Undefined is not a function" or "Undefined is not an object" errors so we believe that this is isolated to iOS7.

- Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_1 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A470a Safari/9537.53
- Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_2 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A501 Safari/9537.53
- Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_3 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B511 Safari/9537.53
- Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53

The `isImmediatePropagationStopped` exception occurs here: 
https://github.com/madrobby/zepto/blob/master/src/event.js#L67
And `isDefaultPrevented` here:
https://github.com/madrobby/zepto/blob/master/src/ajax.js#L21

Unfortunately neither or developers or our QA team have been able to track down a good repo case outside of calling `Object.seal` on the event object manually, which is not being done explicitly to our knowledge (barring proxy code injection or other maladies)

**Comment by madrobby** [comment]
Closing stale issue. Feel free to reopen if this is still an issue.
