### ISSUE TITLE
Tap not firing (IE10 Mobile) 

### ISSUE THREAD

**Issue by baluubas** [madrobby/zepto#932]
This is probably very specific to my use but I figured I create an issue if someone is having the some problem.

On Windows Phone 8, I have a menu with buttons in it. The menu container has  ``overflow: scroll`` and ``touch-action: pan-y`` as the content overflows. The problem occurs when items have to be scrolled into view. An element that was previously outside the boundrys does not receive the first tap event. 

The reason seem to be that when scrolling the menu the deltaX and deltaY properties are updated. But there is no MSPointerUp event fired when scrolling is completed so the delta variables are never reset (probably due to the native scroll). Then when the tap occurs, the old delta is used which is now way off and prevents the tap event from firing. 

The MSGestureEnd event does seem to fire. So my workaround is to add 
``deltaX = deltaY = 0``
to the last line of the MSGeastureEnd event handler.

**Comment by madrobby** [comment]
Dup of #971.
