### ISSUE TITLE
Slow code and lack of quality

### ISSUE THREAD

**Issue by ghost** [madrobby/zepto#947]
Hi
I'm wondering why this code is SO slow and why no one have fixed it? And the quality is bad too. Your selector engine is slooow. Here you easely could have cached the selector to get better result. 

But what is strange is the use of native forEach and indexOf. Both of this is a performance killer. Read this article about indexOf performance: http://stackoverflow.com/questions/6682951/why-is-looping-through-an-array-so-much-faster-than-javascripts-native-indexof

Same with forEach. See the jsperf test here:  http://jsperf.com/for-vs-foreach/9

indexOf could be swapped with a for or while loop and the performance would be better. Your forEach - same. Just use the internal Zepto.each. A for loop.

Overall this will increase the speed. Then I also see that Zepto touches DOM to many times in a bunch of functions. Why? Try avoiding touching DOM. Or if you do, cache the result etc.

There are many other things too that slow down Zepto, but I choose to mention this because I was suprised that the developers didn't know it.

I know this because I was studying Zepto and Jquery because I'm helping out building a new javascript library, and we are in average 80% faster then Zepto. And jquery. You can check some tests here: http://jsperf.com/testers123/22

You also need to cache some of your variabels where you can to speed things up.

**Comment by Volter9** [comment]
I agree with @Kflash. First, I thought that Zepto is a great alternative to jQuery, but in reality it's not that better than jQuery, even their source code's quality 100x better than Zepto's, good try, though:

![Nice try, Zepto](http://i.gyazo.com/cf6db43eddde5ba9bbc31ae2a45a8ee8.png)

No semicolons, no docBlocks, great!
