### ISSUE TITLE
background-size jumping from '100% 100%' to '100%'

### ISSUE THREAD

**Issue by jazzpi** [madrobby/zepto#954]
I've got a minimal example here:

```
<div style="background: url('tris2.png') #f00; width: 100px; height: 30px;
    background-size: 100% 100%;">foo</div>
<script>
$("div").click(function(){$("div").css("border", "3px solid black")});
</script>
```

[Fiddle](http://jsfiddle.net/wW6VM/)

When you click on the div, all that should change is the border. However, the CSS `background-size` property gets set from `100% 100%` (which would resize the background image to perfectly fit the div size) to `100%` (which resizes the background image only horizontally, but not vertically.

**Comment by madrobby** [comment]
Looks like so far, this has been fixed in Chrome, but not in Safari. Closing as this problem is upstream.
