### ISSUE TITLE
No alternative support for $.ajaxSetup

### ISSUE THREAD

**Issue by adaptabi** [madrobby/zepto#986]
Please add similar support

**Comment by RonnyO** [comment]
I just use something like:

```
$.ajaxSettings = $.extend($.ajaxSettings, {
  crossDomain: true,
  // whatever
});
```

**Comment by nanhualyq** [comment]
@RonnyO 
work for me

**Comment by RonnyO** [comment]
Update: turns out adding an `xhrFields ` property to ajaxSettings caused IE10 to choke with an InvalidStateError, my guess is Zepto tries to access these fields too soon. Didn't have time to debug so I had to move away from Zepto for now, if anyone has a solution  or Zepto fixes it, please update.

**Comment by charmpeach** [comment]
Balance between function and lightweight, paradox. Back to jQuery again.

**Comment by madrobby** [comment]
Closing this because we’re not interested in full jQuery compatibility for any price. If there’s a simple solution to add this that doesn’t add lots of complexity, we’re all for adding it, especially if it is done as a module/plugin.
