### ISSUE TITLE
zepto $(document).height()  BUG

### ISSUE THREAD

**Issue by chenweihan** [madrobby/zepto#999]
When CSS postion: absolute, $ (document) .height (), a value of 0. 
Examples:
 
body
div style = "position: absolute; border: 1px solid #ccc;top:0px;left:0px;height:1000px" 
body

jquery is OK!

**Comment by madrobby** [comment]
Hi there! Could you please provide a complete failing example? You can use a site like https://jsfiddle.net to provide that. Without a failing example that we can immediately investigate we can’t reproduce the problem and can’t find and fix the issue. Thank you!
